// src/components/illustrations/registry/subjects.js
// ─────────────────────────────────────────────────────────────────────────────
// THE single place that decides which artwork belongs to which SUBJECT. Scenes and badges are
// mapped in the sibling files scenes.js / badges.js — one folder, every mapping defined once,
// split only so a page that renders a subject picture doesn't also download every scene and badge.
// Nothing else in the repo maps subjects to artwork: data/illustrationThemes.js only re-exports.
//
// SUBJECT → THEME
// Many subjects share one illustration (French, German and Latin are one "languages" picture;
// nine near-identical images would be worse design, not more complete). Resolution:
//   1. normaliseSubject(): case, "&"↔"and", punctuation, diacritics and spacing are folded away,
//      so "Computer Science", "computer  science " and "Computer-Science" are ONE key, and
//      "Art & Design" / "Art and Design" are ONE key — no duplicate entries to maintain.
//   2. The longest whole-word KEYWORD found in the normalised name wins. Whole-word matching
//      matters: "Children and Young People's Workforce" must not hit "pe" (the old Dashboard
//      matcher had exactly that bug) and "physics" must not match "physical education".
//   3. No match → 'generic' (the study-desk composition).
// Variants such as "Biology A", "Geography B" or "Art & Design: Fine Art" resolve through the
// same keywords, so exam-board variants never need their own entries.
//
// This module never edits subjects.js — it only reads names handed to it.
// ─────────────────────────────────────────────────────────────────────────────
import { BiologyArt, ChemistryArt, PhysicsArt, ScienceArt, EnvironmentalScienceArt } from '../subjects/sciences'
import { MathsArt, ComputerScienceArt, DesignTechArt } from '../subjects/stem'
import {
  EnglishArt, HistoryArt, GeographyArt, ReligionPhilosophyArt, PsychologyArt, LawPoliticsArt, LanguagesArt,
} from '../subjects/humanities'
import { ArtArt, MusicArt, DramaArt, MediaArt } from '../subjects/creative'
import { BusinessArt, PEArt, FoodNutritionArt, HealthArt, GenericArt } from '../subjects/applied'

/* ───────────────────────────── subjects ───────────────────────────── */

export const THEMES = [
  'biology', 'chemistry', 'physics', 'science', 'maths', 'english', 'history', 'geography',
  'computerScience', 'languages', 'art', 'music', 'drama', 'pe',
  'religionPhilosophy', 'psychology', 'business', 'lawPolitics', 'media',
  'designTech', 'foodNutrition', 'environmentalScience', 'health', 'generic',
]

/** theme → coded artwork. */
export const THEME_ART = {
  biology: BiologyArt, chemistry: ChemistryArt, physics: PhysicsArt, science: ScienceArt,
  maths: MathsArt, english: EnglishArt, history: HistoryArt, geography: GeographyArt,
  computerScience: ComputerScienceArt, languages: LanguagesArt, art: ArtArt, music: MusicArt,
  drama: DramaArt, pe: PEArt, religionPhilosophy: ReligionPhilosophyArt, psychology: PsychologyArt,
  business: BusinessArt, lawPolitics: LawPoliticsArt, media: MediaArt, designTech: DesignTechArt,
  foodNutrition: FoodNutritionArt, environmentalScience: EnvironmentalScienceArt, health: HealthArt,
  generic: GenericArt,
}

/**
 * Replace any coded theme with a commissioned/raster image later by setting its path here
 * (e.g. biology: '/illustrations/biology.webp'). SubjectIllustration prefers an asset when set.
 */
export const THEME_ASSETS = Object.fromEntries(THEMES.map((t) => [t, null]))

/**
 * Compact-tier framing. At ≤72px a subject is drawn without its disc and foliage, so the 240-unit
 * canvas would leave the object floating in padding. These per-theme viewBoxes crop to each
 * object's measured bounds (+5% margin) so every tile fills consistently. Generated by measuring
 * the compact render in headless Chromium (getBBox); re-measure if a compact composition changes.
 */
export const COMPACT_VIEWBOX = {
  biology: '10 1 221 221',
  chemistry: '31 40 178 178',
  physics: '12 10 216 216',
  science: '31 40 178 178',
  maths: '32 27 178 178',
  english: '22 38 201 201',
  history: '37 55 156 156',
  geography: '15 12 206 206',
  computerScience: '36 63 168 168',
  languages: '34 36 179 179',
  art: '43 45 161 161',
  music: '50 70 143 143',
  drama: '20 30 206 206',
  pe: '28 22 183 183',
  religionPhilosophy: '51 67 142 142',
  psychology: '26 39 192 192',
  business: '49 33 152 152',
  lawPolitics: '25 34 189 189',
  media: '24 25 181 181',
  designTech: '44 60 149 149',
  foodNutrition: '36 59 169 169',
  environmentalScience: '28 44 184 184',
  health: '38 43 164 164',
  generic: '22 40 201 201',
}

/** theme → plain-language keywords (matched as whole words after normalisation). */
const THEME_KEYWORDS = {
  biology: ['biology', 'human biology'],
  chemistry: ['chemistry'],
  physics: ['physics', 'astronomy'],
  science: ['science', 'combined science', 'applied science'],
  maths: ['mathematics', 'maths', 'math', 'further mathematics', 'statistics', 'mathematical'],
  english: ['english', 'literature', 'creative writing'],
  history: ['history', 'ancient history', 'classical civilisation', 'classical civilization', 'archaeology'],
  geography: ['geography', 'travel and tourism', 'tourism', 'geology'],
  computerScience: ['computer science', 'computing', 'information technology', 'ict', 'esports', 'digital'],
  languages: [
    'languages', 'modern foreign languages', 'french', 'german', 'spanish', 'italian', 'portuguese',
    'russian', 'turkish', 'arabic', 'persian', 'farsi', 'japanese', 'korean', 'dutch', 'gujarati',
    'bengali', 'panjabi', 'punjabi', 'urdu', 'polish', 'latin', 'greek', 'classical greek',
    'hebrew', 'mandarin', 'chinese', 'cantonese', 'welsh', 'irish', 'gaelic',
  ],
  art: ['art', 'art and design', 'art craft and design', 'photography', 'fine art', 'graphic communication', 'graphic design', 'textile design'],
  music: ['music', 'music technology'],
  drama: ['drama', 'dance', 'theatre', 'theatre studies', 'performing arts'],
  pe: ['physical education', 'sport', 'sports', 'exercise', 'fitness', 'sport and exercise science', 'exercise science'],
  religionPhilosophy: ['religious studies', 'religious education', 'religion', 'philosophy', 'theology', 'ethics', 'biblical studies'],
  psychology: ['psychology', 'sociology', 'social science', 'criminology', 'anthropology'],
  business: ['business', 'business studies', 'economics', 'accounting', 'enterprise', 'finance', 'financial', 'marketing', 'retail', 'management'],
  lawPolitics: ['law', 'politics', 'government and politics', 'citizenship', 'public services', 'forensic', 'criminal', 'political', 'international relations'],
  media: ['media', 'media studies', 'film', 'film studies', 'creative media', 'journalism'],
  designTech: [
    'design and technology', 'technology and design', 'product design', 'engineering', 'construction',
    'vehicle', 'land based technology', 'textiles', 'electronics',
  ],
  foodNutrition: ['food', 'nutrition', 'food science', 'hospitality', 'catering', 'cookery', 'home economics'],
  environmentalScience: [
    'environmental', 'environmental science', 'land and environment', 'animal care', 'animal management',
    'animal science', 'agriculture', 'horticulture', 'earth science', 'countryside',
  ],
  health: ['health', 'health and social care', 'health science', 'social care', 'childcare', 'children', 'childhood', 'early years', 'nursing', 'care'],
}

/** Fold a subject name to its canonical lookup form (see header). Exported for the QA script & callers. */
export function normaliseSubject(name) {
  return String(name ?? '')
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/[^a-z0-9]+/g, ' ')
    .trim()
    .replace(/\s+/g, ' ')
}

// Longest keyword first so "environmental science" beats "science", "computer science" beats "science".
const KEYWORD_INDEX = Object.entries(THEME_KEYWORDS)
  .flatMap(([theme, words]) => words.map((w) => [` ${normaliseSubject(w)} `, theme, normaliseSubject(w).length]))
  .sort((a, b) => b[2] - a[2])

const themeCache = new Map()

/** subject name (any casing/punctuation) → theme id. Unknown / empty → 'generic'. */
export function themeForSubject(subjectName) {
  const key = normaliseSubject(subjectName)
  if (!key) return 'generic'
  if (themeCache.has(key)) return themeCache.get(key)
  const padded = ` ${key} `
  const hit = KEYWORD_INDEX.find(([kw]) => padded.includes(kw))
  const theme = hit ? hit[1] : 'generic'
  themeCache.set(key, theme)
  return theme
}

/** Raster/commissioned asset path for this subject's theme, or null (coded artwork is used). */
export function assetForSubject(subjectName) {
  return THEME_ASSETS[themeForSubject(subjectName)] || null
}
